// EasyVerbs
// Copyright (C) 2026 EzyLabsHQ
// This program is free software under GPL v3 - see LICENSE

// Общие данные глаголов и переводы (используются полной и облегчённой версиями)
const verbsData = [
    { v1: "be", v2: "was/were", v3: "been", translation: "быть", complexity: 1 },
    { v1: "bear", v2: "bore", v3: "born(e)", translation: "терпеть, выдерживать", complexity: 3 },
    { v1: "beat", v2: "beat", v3: "beaten", translation: "бить", complexity: 1 },
    { v1: "become", v2: "became", v3: "become", translation: "становиться", complexity: 1 },
    { v1: "begin", v2: "began", v3: "begun", translation: "начинать", complexity: 1 },
    { v1: "bite", v2: "bit", v3: "bitten", translation: "кусать", complexity: 2 },
    { v1: "blow", v2: "blew", v3: "blown", translation: "дуть", complexity: 2 },
    { v1: "break", v2: "broke", v3: "broken", translation: "ломать", complexity: 1 },
    { v1: "bring", v2: "brought", v3: "brought", translation: "приносить", complexity: 1 },
    { v1: "build", v2: "built", v3: "built", translation: "строить", complexity: 2 },
    { v1: "burn", v2: "burnt/burned", v3: "burnt/burned", translation: "гореть", complexity: 2 },
    { v1: "burst", v2: "burst", v3: "burst", translation: "взрывать(ся)", complexity: 3 },
    { v1: "buy", v2: "bought", v3: "bought", translation: "покупать", complexity: 1 },
    { v1: "can", v2: "could", v3: "been able", translation: "мочь; уметь", complexity: 1 },
    { v1: "catch", v2: "caught", v3: "caught", translation: "ловить", complexity: 2 },
    { v1: "choose", v2: "chose", v3: "chosen", translation: "выбирать", complexity: 2 },
    { v1: "come", v2: "came", v3: "come", translation: "приходить", complexity: 1 },
    { v1: "cost", v2: "cost", v3: "cost", translation: "стоить", complexity: 2 },
    { v1: "cut", v2: "cut", v3: "cut", translation: "резать", complexity: 1 },
    { v1: "deal", v2: "dealt", v3: "dealt", translation: "иметь дело", complexity: 3 },
    { v1: "dig", v2: "dug", v3: "dug", translation: "копать", complexity: 2 },
    { v1: "do", v2: "did", v3: "done", translation: "делать", complexity: 1 },
    { v1: "draw", v2: "drew", v3: "drawn", translation: "рисовать", complexity: 2 },
    { v1: "dream", v2: "dreamt/dreamed", v3: "dreamt/dreamed", translation: "мечтать", complexity: 2 },
    { v1: "drink", v2: "drank", v3: "drunk", translation: "пить", complexity: 1 },
    { v1: "drive", v2: "drove", v3: "driven", translation: "водить (авто)", complexity: 2 },
    { v1: "eat", v2: "ate", v3: "eaten", translation: "есть", complexity: 1 },
    { v1: "fall", v2: "fell", v3: "fallen", translation: "падать", complexity: 2 },
    { v1: "feed", v2: "fed", v3: "fed", translation: "кормить", complexity: 2 },
    { v1: "feel", v2: "felt", v3: "felt", translation: "чувствовать", complexity: 1 },
    { v1: "fight", v2: "fought", v3: "fought", translation: "сражаться; бороться", complexity: 2 },
    { v1: "find", v2: "found", v3: "found", translation: "находить", complexity: 1 },
    { v1: "fly", v2: "flew", v3: "flown", translation: "летать", complexity: 2 },
    { v1: "forbid", v2: "forbade", v3: "forbidden", translation: "запрещать", complexity: 3 },
    { v1: "forget", v2: "forgot", v3: "forgotten", translation: "забывать", complexity: 2 },
    { v1: "forgive", v2: "forgave", v3: "forgiven", translation: "прощать", complexity: 2 },
    { v1: "freeze", v2: "froze", v3: "frozen", translation: "замерзать", complexity: 3 },
    { v1: "get", v2: "got/gotten", v3: "got/gotten", translation: "получать", complexity: 1 },
    { v1: "give", v2: "gave", v3: "given", translation: "давать", complexity: 1 },
    { v1: "go", v2: "went", v3: "gone", translation: "идти", complexity: 1 },
    { v1: "grow", v2: "grew", v3: "grown", translation: "расти", complexity: 2 },
    { v1: "have", v2: "had", v3: "had", translation: "иметь", complexity: 1 },
    { v1: "hear", v2: "heard", v3: "heard", translation: "слышать", complexity: 2 },
    { v1: "hide", v2: "hid", v3: "hidden", translation: "прятать(ся)", complexity: 2 },
    { v1: "hit", v2: "hit", v3: "hit", translation: "бить", complexity: 1 },
    { v1: "hold", v2: "held", v3: "held", translation: "держать", complexity: 2 },
    { v1: "hurt", v2: "hurt", v3: "hurt", translation: "обижать, делать больно", complexity: 2 },
    { v1: "keep", v2: "kept", v3: "kept", translation: "хранить", complexity: 2 },
    { v1: "know", v2: "knew", v3: "known", translation: "знать", complexity: 1 },
    { v1: "lead", v2: "led", v3: "led", translation: "вести", complexity: 2 },
    { v1: "learn", v2: "learnt/learned", v3: "learnt/learned", translation: "учить(ся)", complexity: 1 },
    { v1: "leave", v2: "left", v3: "left", translation: "оставлять, покидать", complexity: 1 },
    { v1: "lend", v2: "lent", v3: "lent", translation: "одалживать", complexity: 3 },
    { v1: "let", v2: "let", v3: "let", translation: "позволять", complexity: 1 },
    { v1: "light", v2: "lit", v3: "lit", translation: "зажигать", complexity: 2 },
    { v1: "lose", v2: "lost", v3: "lost", translation: "терять", complexity: 1 },
    { v1: "make", v2: "made", v3: "made", translation: "делать", complexity: 1 },
    { v1: "mean", v2: "meant", v3: "meant", translation: "подразумевать", complexity: 2 },
    { v1: "meet", v2: "met", v3: "met", translation: "встречать", complexity: 1 },
    { v1: "pay", v2: "paid", v3: "paid", translation: "платить", complexity: 2 },
    { v1: "put", v2: "put", v3: "put", translation: "класть", complexity: 1 },
    { v1: "read", v2: "read", v3: "read", translation: "читать", complexity: 1 },
    { v1: "ride", v2: "rode", v3: "ridden", translation: "ездить (верхом)", complexity: 3 },
    { v1: "ring", v2: "rang", v3: "rung", translation: "звонить", complexity: 2 },
    { v1: "rise", v2: "rose", v3: "risen", translation: "поднимать", complexity: 3 },
    { v1: "run", v2: "ran", v3: "run", translation: "бежать", complexity: 1 },
    { v1: "say", v2: "said", v3: "said", translation: "говорить", complexity: 1 },
    { v1: "see", v2: "saw", v3: "seen", translation: "видеть", complexity: 1 },
    { v1: "sell", v2: "sold", v3: "sold", translation: "продавать", complexity: 2 },
    { v1: "send", v2: "sent", v3: "sent", translation: "отправлять", complexity: 2 },
    { v1: "set", v2: "set", v3: "set", translation: "устанавливать", complexity: 3 },
    { v1: "sew", v2: "sewed", v3: "sewn", translation: "шить", complexity: 3 },
    { v1: "shake", v2: "shook", v3: "shaken", translation: "трясти", complexity: 2 },
    { v1: "shine", v2: "shone", v3: "shone", translation: "светить", complexity: 2 },
    { v1: "shoot", v2: "shot", v3: "shot", translation: "стрелять", complexity: 3 },
    { v1: "show", v2: "showed", v3: "shown", translation: "показывать", complexity: 2 },
    { v1: "shut", v2: "shut", v3: "shut", translation: "закрывать", complexity: 3 },
    { v1: "sing", v2: "sang", v3: "sung", translation: "петь", complexity: 2 },
    { v1: "sit", v2: "sat", v3: "sat", translation: "сидеть", complexity: 1 },
    { v1: "sleep", v2: "slept", v3: "slept", translation: "спать", complexity: 1 },
    { v1: "smell", v2: "smelt/smelled", v3: "smelt/smelled", translation: "пахнуть, нюхать", complexity: 3 },
    { v1: "speak", v2: "spoke", v3: "spoken", translation: "говорить", complexity: 2 },
    { v1: "spell", v2: "spelt/spelled", v3: "spelt/spelled", translation: "называть по буквам", complexity: 3 },
    { v1: "spend", v2: "spent", v3: "spent", translation: "тратить", complexity: 2 },
    { v1: "stand", v2: "stood", v3: "stood", translation: "стоять", complexity: 2 },
    { v1: "steal", v2: "stole", v3: "stolen", translation: "воровать", complexity: 2 },
    { v1: "stick", v2: "stuck", v3: "stuck", translation: "приклеивать(ся)", complexity: 3 },
    { v1: "sting", v2: "stung", v3: "stung", translation: "жалить", complexity: 3 },
    { v1: "swear", v2: "swore", v3: "sworn", translation: "клясться", complexity: 3 },
    { v1: "sweep", v2: "swept", v3: "swept", translation: "подметать", complexity: 3 },
    { v1: "swim", v2: "swam", v3: "swum", translation: "плавать", complexity: 2 },
    { v1: "take", v2: "took", v3: "taken", translation: "брать", complexity: 1 },
    { v1: "teach", v2: "taught", v3: "taught", translation: "обучать", complexity: 2 },
    { v1: "tear", v2: "tore", v3: "torn", translation: "рвать", complexity: 3 },
    { v1: "tell", v2: "told", v3: "told", translation: "рассказывать", complexity: 1 },
    { v1: "think", v2: "thought", v3: "thought", translation: "думать", complexity: 1 },
    { v1: "throw", v2: "threw", v3: "thrown", translation: "бросать", complexity: 2 },
    { v1: "understand", v2: "understood", v3: "understood", translation: "понимать", complexity: 2 },
    { v1: "wake", v2: "woke", v3: "woken", translation: "просыпаться; будить", complexity: 2 },
    { v1: "wear", v2: "wore", v3: "worn", translation: "носить (одежду)", complexity: 2 },
    { v1: "win", v2: "won", v3: "won", translation: "выигрывать", complexity: 2 },
    { v1: "write", v2: "wrote", v3: "written", translation: "писать", complexity: 1 }
];

const verbTranslations = {
    es: {
        be: 'ser, estar',
        bear: 'soportar, aguantar',
        beat: 'golpear, vencer',
        become: 'convertirse en',
        begin: 'empezar',
        bite: 'morder',
        blow: 'soplar',
        break: 'romper',
        bring: 'traer',
        build: 'construir',
        burn: 'quemar(se)',
        burst: 'explotar, reventar',
        buy: 'comprar',
        can: 'poder; saber',
        catch: 'atrapar',
        choose: 'elegir',
        come: 'venir',
        cost: 'costar',
        cut: 'cortar',
        deal: 'tratar, tener que ver',
        dig: 'cavar',
        do: 'hacer',
        draw: 'dibujar',
        dream: 'soñar',
        drink: 'beber',
        drive: 'conducir',
        eat: 'comer',
        fall: 'caer',
        feed: 'alimentar',
        feel: 'sentir',
        fight: 'pelear; luchar',
        find: 'encontrar',
        fly: 'volar',
        forbid: 'prohibir',
        forget: 'olvidar',
        forgive: 'perdonar',
        freeze: 'congelar(se)',
        get: 'obtener',
        give: 'dar',
        go: 'ir',
        grow: 'crecer',
        have: 'tener',
        hear: 'oír',
        hide: 'esconder(se)',
        hit: 'golpear',
        hold: 'sostener',
        hurt: 'lastimar, hacer daño',
        keep: 'guardar',
        know: 'saber, conocer',
        lead: 'conducir, guiar',
        learn: 'aprender',
        leave: 'dejar, salir de',
        lend: 'prestar',
        let: 'permitir',
        light: 'encender',
        lose: 'perder',
        make: 'hacer',
        mean: 'significar',
        meet: 'encontrarse con',
        pay: 'pagar',
        put: 'poner',
        read: 'leer',
        ride: 'montar (a caballo)',
        ring: 'sonar, llamar',
        rise: 'subir, elevarse',
        run: 'correr',
        say: 'decir',
        see: 'ver',
        sell: 'vender',
        send: 'enviar',
        set: 'fijar, establecer',
        sew: 'coser',
        shake: 'sacudir',
        shine: 'brillar',
        shoot: 'disparar',
        show: 'mostrar',
        shut: 'cerrar',
        sing: 'cantar',
        sit: 'sentarse',
        sleep: 'dormir',
        smell: 'oler, olfatear',
        speak: 'hablar',
        spell: 'deletrear',
        spend: 'gastar',
        stand: 'estar de pie',
        steal: 'robar',
        stick: 'pegar(se)',
        sting: 'picar',
        swear: 'jurar',
        sweep: 'barrer',
        swim: 'nadar',
        take: 'tomar',
        teach: 'enseñar',
        tear: 'rasgar',
        tell: 'contar, decir',
        think: 'pensar',
        throw: 'tirar, lanzar',
        understand: 'entender',
        wake: 'despertar(se)',
        wear: 'llevar (ropa)',
        win: 'ganar',
        write: 'escribir',
    },
    de: {
        be: 'sein',
        bear: 'ertragen, aushalten',
        beat: 'schlagen',
        become: 'werden',
        begin: 'beginnen',
        bite: 'beißen',
        blow: 'blasen',
        break: 'brechen',
        bring: 'bringen',
        build: 'bauen',
        burn: 'brennen',
        burst: 'platzen, bersten',
        buy: 'kaufen',
        can: 'können',
        catch: 'fangen',
        choose: 'wählen',
        come: 'kommen',
        cost: 'kosten',
        cut: 'schneiden',
        deal: 'zu tun haben mit',
        dig: 'graben',
        do: 'machen, tun',
        draw: 'zeichnen',
        dream: 'träumen',
        drink: 'trinken',
        drive: 'fahren',
        eat: 'essen',
        fall: 'fallen',
        feed: 'füttern',
        feel: 'fühlen',
        fight: 'kämpfen',
        find: 'finden',
        fly: 'fliegen',
        forbid: 'verbieten',
        forget: 'vergessen',
        forgive: 'vergeben',
        freeze: 'einfrieren',
        get: 'bekommen',
        give: 'geben',
        go: 'gehen',
        grow: 'wachsen',
        have: 'haben',
        hear: 'hören',
        hide: 'verstecken (sich)',
        hit: 'schlagen, treffen',
        hold: 'halten',
        hurt: 'verletzen, wehtun',
        keep: 'behalten, aufbewahren',
        know: 'wissen, kennen',
        lead: 'führen',
        learn: 'lernen',
        leave: 'verlassen',
        lend: 'verleihen, leihen',
        let: 'lassen, erlauben',
        light: 'anzünden',
        lose: 'verlieren',
        make: 'machen',
        mean: 'bedeuten',
        meet: 'treffen',
        pay: 'bezahlen',
        put: 'legen, stellen',
        read: 'lesen',
        ride: 'reiten',
        ring: 'klingeln, läuten',
        rise: 'steigen, aufgehen',
        run: 'rennen, laufen',
        say: 'sagen',
        see: 'sehen',
        sell: 'verkaufen',
        send: 'senden, schicken',
        set: 'setzen, festlegen',
        sew: 'nähen',
        shake: 'schütteln',
        shine: 'scheinen',
        shoot: 'schießen',
        show: 'zeigen',
        shut: 'schließen',
        sing: 'singen',
        sit: 'sitzen',
        sleep: 'schlafen',
        smell: 'riechen',
        speak: 'sprechen',
        spell: 'buchstabieren',
        spend: 'ausgeben',
        stand: 'stehen',
        steal: 'stehlen',
        stick: 'kleben, stecken',
        sting: 'stechen',
        swear: 'schwören',
        sweep: 'fegen',
        swim: 'schwimmen',
        take: 'nehmen',
        teach: 'lehren, unterrichten',
        tear: 'reißen',
        tell: 'erzählen, sagen',
        think: 'denken',
        throw: 'werfen',
        understand: 'verstehen',
        wake: 'aufwachen; wecken',
        wear: 'tragen (Kleidung)',
        win: 'gewinnen',
        write: 'schreiben',
    },
    fr: {
        be: 'être',
        bear: 'supporter, endurer',
        beat: 'battre',
        become: 'devenir',
        begin: 'commencer',
        bite: 'mordre',
        blow: 'souffler',
        break: 'casser',
        bring: 'apporter',
        build: 'construire',
        burn: 'brûler',
        burst: 'éclater, exploser',
        buy: 'acheter',
        can: 'pouvoir; savoir',
        catch: 'attraper',
        choose: 'choisir',
        come: 'venir',
        cost: 'coûter',
        cut: 'couper',
        deal: 'avoir affaire à',
        dig: 'creuser',
        do: 'faire',
        draw: 'dessiner',
        dream: 'rêver',
        drink: 'boire',
        drive: 'conduire',
        eat: 'manger',
        fall: 'tomber',
        feed: 'nourrir',
        feel: 'sentir',
        fight: 'se battre; lutter',
        find: 'trouver',
        fly: 'voler',
        forbid: 'interdire',
        forget: 'oublier',
        forgive: 'pardonner',
        freeze: 'geler',
        get: 'obtenir',
        give: 'donner',
        go: 'aller',
        grow: 'pousser, grandir',
        have: 'avoir',
        hear: 'entendre',
        hide: 'cacher (se)',
        hit: 'frapper',
        hold: 'tenir',
        hurt: 'blesser, faire mal',
        keep: 'garder',
        know: 'savoir, connaître',
        lead: 'mener, diriger',
        learn: 'apprendre',
        leave: 'quitter, laisser',
        lend: 'prêter',
        let: 'permettre, laisser',
        light: 'allumer',
        lose: 'perdre',
        make: 'faire',
        mean: 'signifier',
        meet: 'rencontrer',
        pay: 'payer',
        put: 'mettre, poser',
        read: 'lire',
        ride: 'monter (à cheval)',
        ring: 'sonner',
        rise: 'se lever, monter',
        run: 'courir',
        say: 'dire',
        see: 'voir',
        sell: 'vendre',
        send: 'envoyer',
        set: 'fixer, établir',
        sew: 'coudre',
        shake: 'secouer',
        shine: 'briller',
        shoot: 'tirer',
        show: 'montrer',
        shut: 'fermer',
        sing: 'chanter',
        sit: 's\'asseoir, être assis',
        sleep: 'dormir',
        smell: 'sentir, flairer',
        speak: 'parler',
        spell: 'épeler',
        spend: 'dépenser',
        stand: 'être debout',
        steal: 'voler',
        stick: 'coller (se)',
        sting: 'piquer',
        swear: 'jurer',
        sweep: 'balayer',
        swim: 'nager',
        take: 'prendre',
        teach: 'enseigner',
        tear: 'déchirer',
        tell: 'raconter, dire',
        think: 'penser',
        throw: 'jeter, lancer',
        understand: 'comprendre',
        wake: 'se réveiller; réveiller',
        wear: 'porter (vêtement)',
        win: 'gagner',
        write: 'écrire',
    },
    pt: {
        be: 'ser, estar',
        bear: 'suportar, aguentar',
        beat: 'bater, derrotar',
        become: 'tornar-se',
        begin: 'começar',
        bite: 'morder',
        blow: 'soprar',
        break: 'quebrar',
        bring: 'trazer',
        build: 'construir',
        burn: 'queimar(-se)',
        burst: 'explodir, arrebentar',
        buy: 'comprar',
        can: 'poder; saber',
        catch: 'pegar, capturar',
        choose: 'escolher',
        come: 'vir',
        cost: 'custar',
        cut: 'cortar',
        deal: 'lidar com',
        dig: 'cavar',
        do: 'fazer',
        draw: 'desenhar',
        dream: 'sonhar',
        drink: 'beber',
        drive: 'dirigir',
        eat: 'comer',
        fall: 'cair',
        feed: 'alimentar',
        feel: 'sentir',
        fight: 'lutar; brigar',
        find: 'encontrar',
        fly: 'voar',
        forbid: 'proibir',
        forget: 'esquecer',
        forgive: 'perdoar',
        freeze: 'congelar(-se)',
        get: 'obter, conseguir',
        give: 'dar',
        go: 'ir',
        grow: 'crescer',
        have: 'ter',
        hear: 'ouvir',
        hide: 'esconder(-se)',
        hit: 'bater, atingir',
        hold: 'segurar',
        hurt: 'machucar, ferir',
        keep: 'guardar',
        know: 'saber, conhecer',
        lead: 'conduzir, liderar',
        learn: 'aprender',
        leave: 'deixar, partir de',
        lend: 'emprestar',
        let: 'permitir, deixar',
        light: 'acender',
        lose: 'perder',
        make: 'fazer',
        mean: 'significar',
        meet: 'encontrar-se com',
        pay: 'pagar',
        put: 'colocar',
        read: 'ler',
        ride: 'andar (a cavalo)',
        ring: 'tocar, soar',
        rise: 'subir, elevar-se',
        run: 'correr',
        say: 'dizer',
        see: 'ver',
        sell: 'vender',
        send: 'enviar',
        set: 'definir, estabelecer',
        sew: 'costurar',
        shake: 'sacudir',
        shine: 'brilhar',
        shoot: 'atirar',
        show: 'mostrar',
        shut: 'fechar',
        sing: 'cantar',
        sit: 'sentar-se',
        sleep: 'dormir',
        smell: 'cheirar, sentir o cheiro',
        speak: 'falar',
        spell: 'soletrar',
        spend: 'gastar',
        stand: 'ficar em pé',
        steal: 'roubar',
        stick: 'colar(-se)',
        sting: 'picar',
        swear: 'jurar',
        sweep: 'varrer',
        swim: 'nadar',
        take: 'pegar, levar',
        teach: 'ensinar',
        tear: 'rasgar',
        tell: 'contar, dizer',
        think: 'pensar',
        throw: 'jogar, lançar',
        understand: 'entender',
        wake: 'acordar; despertar',
        wear: 'usar (roupa)',
        win: 'vencer, ganhar',
        write: 'escrever',
    }
};
